name: test-workflow with cron

on:
  schedule:
  - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Git configuration
      run: git config --global user.name "Test bot"