name: test-workflow with push

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Git configuration
      run: git config --global user.name "Test bot"
    - name: Download test file
      run: curl --insecure --request GET https://raw.githubusercontent.com/stanislawkuich/test_github_actions/master/test.txt
    - name: Display structure of downloaded files
      run: ls -R
    - name: Commit
      run: |
        git add test.txt
        git diff --exit-code || git commit -m "auto update"
        git push
