name: test-workflow with cron

on:
  schedule:
    - cron: '24 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: echo "This step will always run"
